
export const ADD_INGREDEIENTS = 'ADD_INGREDEIENTS';
export const ADD_INGREDEIENTS_TO_MIDDLE = 'ADD_INGREDEIENTS_TO_MIDDLE';
export const UPDATE_BURGER_VALUE = 'UPDATE_BURGER_VALUE';
export const REMOVE_INGREDIENT_FROM_BURGER = 'REMOVE_INGREDIENT_FROM_BURGER';

export const START_BURGER = 'START BURGER';

