export const  LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS= 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE= 'LOGIN_USER_FAILURE';

export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE';

export const SIGNUP_EMAIL_CONFIRM = 'SIGNUP_EMAIL_CONFIRM';
export const SIGNUP_EMAIL_CONFIRM_SUCCESS = 'SIGNUP_EMAIL_CONFIRM_SUCCESS';
export const SIGNUP_EMAIL_CONFIRM_FAILURE = 'SIGNUP_EMAIL_CONFIRM_FAILURE';

export const  LOGOUT_USER = 'LOGOUT_USER';

